insert = input("투입금액")
price = input("물건값")
rtn = int(insert) - int(price)
print("거스름돈 ")
print(rtn)
print("500원 동전의 개수 : ")
gob = int(rtn/500)
print(gob)
print("100원 동전의 개수 : ")
print(int((rtn - gob*500)/100))
